### ISSUE TITLE
Session 2 Todo

### ISSUE THREAD

**Issue by Dakuider** [Dakuider/Eallfedem#13]
- [ ] flesh out Devden characteristics
- [ ] create character around orog
- [ ] figure out where players are going next and why

**Comment by Dakuider** [comment]
Do Lillied guards care about Stewie in the morning?

**Comment by Dakuider** [comment]
Players wake up in prison because of Elyas / Rivas ???
